database:
  type: "SQLITE" # Options: SQLITE, MARIADB
  host: "localhost"
  username: "database"
  password: "database"
  database: "database"
  port: 3306
  pools: 6
formatter:
  days: "d"
  hours: "h"
  minutes: "m"
  seconds: "s"
messages:
  permanent-banned:
    - "<red>You are banned from this server</red>"
    - "<red>Reason: {reason}</red>"
    - "<red>Banned by: {author}</red>"
  temp-banned:
    - "<red>You are banned from this server</red>"
    - "<red>Reason: {reason}</red>"
    - "<red>Banned by: {author}</red>"
    - "<red>Until: {time}</red>"
  kick:
    - "<red>You are kicked from this server</red>"
    - "<red>Reason: {reason}</red>"
    - "<red>Kicked by: {author}</red>"
  permanent-mute:
    - "<red>You are muted from this server</red>"
    - "<red>Reason: {reason}</red>"
    - "<red>Muted by: {author}</red>"
  temp-mute:
    - "<red>You are muted from this server</red>"
    - "<red>Reason: {reason}</red>"
    - "<red>Muted by: {author}</red>"
    - "<red>Until: {time}</red>"

gui-history:
  main:
    title: "<dark_purple>History of {player}</dark_purple>"
    lore:
      - "<gray>Player:</gray> <white>{player}</white>"
      - "<gray>Author:</gray> <red>{author}</red>"
      - "<gray>Reason:</gray> <white>{reason}</white>"
      - "<gray>Type:</gray> <yellow>{type}</yellow>"
      - "<gray>IP:</gray> <white>{ip}</white>"
      - "<gray>Expires:</gray> <gold>{time}</gold>"
      - "<gray>ID:</gray> <blue>{id}</blue>"
      - "<gray>Active:</gray> <green>{active}</green>"

